### ISSUE TITLE
Button tokens in Magister theme

### ISSUE THREAD

**Issue by DanielleRameau** [sanomalearning/design-system#161]
|<div align="left">**What is the problem we are solving and why?**|
|-------------|
|As a user, I want to have accessible and a consistent buttons, so I can perform my actions quickly| 
|As a developer, I want to have an easy to use button component, so I can quickly implement actions in the user interface of the product|
|As a designer, I want to have clear UX documentation and an easy to use Figma component of a button, so I can quickly create actions in my prototypes| 

## Description
The button component needs tokens for the Magister theme.

## Design
The design of current Magister buttons can be found in Abstract.

```[tasklist]
### Tasks
- [x] Base button tokens of Magister
- [x] Light mode button tokens of Magister
- [ ] Dark mode button tokens of Magister
- [x] Give "link" style buttons their own tokens for all the states (now they use the "outline" tokens)
- [ ] color contrast check
```

**Comment by DanielleRameau** [comment]
Jeremy tested the Magister button and approved the Figma component
