### ISSUE TITLE
Button tokens in ItsLearning theme

### ISSUE THREAD

**Issue by DanielleRameau** [sanomalearning/design-system#162]
# Button tokens in ItsLearning theme
**This user story is part of feature https://github.com/sanomalearning/design-system/issues/160**

|<div align="left">**What is the problem we are solving and why?**|
|-------------|
|As a user, I want to have accessible and a consistent buttons, so I can perform my actions quickly| 
|As a developer, I want to have an easy to use button component, so I can quickly implement actions in the user interface of the product|
|As a designer, I want to have clear UX documentation and an easy to use Figma component of a button, so I can quickly create actions in my prototypes| 

## Description
The button component needs tokens for the ItsLearning theme.

## Design
Ask UX team where we can find the current buttons of ItsLearning

## Tasks
- [ ] Ask UX team where we can find the current buttons of ItsLearning
- [ ] Base button tokens of ItsLearning
- [ ] Light mode button tokens of ItsLearning
- [ ] Dark mode button tokens of ItsLearning
