### ISSUE TITLE
Button tokens in Bingel theme

### ISSUE THREAD

**Issue by DanielleRameau** [sanomalearning/design-system#164]
# Button tokens in Bingel theme
**This user story is part of feature https://github.com/sanomalearning/design-system/issues/160**

|<div align="left">**What is the problem we are solving and why?**|
|-------------|
|As a user, I want to have accessible and a consistent buttons, so I can perform my actions quickly| 
|As a developer, I want to have an easy to use button component, so I can quickly implement actions in the user interface of the product|
|As a designer, I want to have clear UX documentation and an easy to use Figma component of a button, so I can quickly create actions in my prototypes| 

## Description
The button component needs tokens for the Bingel theme.

## Design
There are currently 2 Bingel products with different styling, the SL DS team will create a proposal for the design and will discuss this with the development teams.

## Tasks
- [ ] Ask UX team where we can find the current buttons of Bingel DC and Bingel INT
- [ ] Design of Bingel buttons
- [ ] Base button tokens of Bingel
- [ ] Light mode button tokens of Bingel
- [ ] Dark mode button tokens of Bingel

**Comment by DanielleRameau** [comment]
@RoaldBoerema could you check the sizing here as well?
