### ISSUE TITLE
Button tokens in Max theme

### ISSUE THREAD

**Issue by DanielleRameau** [sanomalearning/design-system#166]
|<div align="left">**What is the problem we are solving and why?**|
|-------------|
|As a user, I want to have accessible and a consistent buttons, so I can perform my actions quickly| 
|As a developer, I want to have an easy to use button component, so I can quickly implement actions in the user interface of the product|
|As a designer, I want to have clear UX documentation and an easy to use Figma component of a button, so I can quickly create actions in my prototypes| 

## Design
Create proposal based on Max online figma files

```[tasklist]
### Tasks
- [ ] Base button tokens of Max
- [ ] Light mode button tokens of Max
- [ ] Dark mode button tokens of Max
```
