### ISSUE TITLE
UI design of explore section

### ISSUE THREAD

**Issue by DanielleRameau** [sanomalearning/design-system#181]
## UI design of explore section
**This task is part of https://github.com/sanomalearning/design-system/issues/180**

## Description
Based on the outcome of the design ideation we created a wireframe of the explore section in all breakpoints.
To develop this we need to create a high-fidelity design. The cards should be available in all states:
- idle
- hover
- focused
- active

Share ideas around animation as well (zoom effect?)

## Wireframe
Share link of wireframe here (see issue https://github.com/sanomalearning/design-system/issues/176)

```[tasklist]
### Tasks
- [x] Create high fidelity design for mobile (light mode/dark mode)
- [x] Create high fidelity design for tablet portrait (light mode)
- [x] Create visual for 'guidelines'
```
