### ISSUE TITLE
First draft UX documentation help text

### ISSUE THREAD

**Issue by DanielleRameau** [sanomalearning/design-system#228]
## Description
Help text provides either an informative description or an error message that gives more context about what a user needs to input. It’s commonly used in forms. Create first draft of UX documentation regarding the help text.

## Examples
https://spectrum.adobe.com/page/help-text/
https://paste.twilio.design/components/help-text/

```[tasklist]
### Tasks
- [ ] What is an input field? / introduction text
- [ ] What are the key points?
- [ ] Types
- [ ] Anatomy
- [ ] Behaviors
- [ ] How to use
- [ ] Responsiveness
- [ ] Content
- [ ] Interaction (accessibility)
- [ ] Behavior (accessibility)
- [ ] Labeling (accessibility)
- [ ] Recommendations (accessibility)
- [ ] Add a draft title or issue reference here
```

@DanielleRameau put help text in in the stories of the specific form controls
