### ISSUE TITLE
Prepare website environment

### ISSUE THREAD

**Issue by DanielleRameau** [sanomalearning/design-system#23]
**Description**
Prepare environment of sanomalearning.design so we can start with the development of the documentation website.

**TODO**

- [x] Web server (azure devops or GitHub Pages)
- [x] Deployment process (GitHub action)
- [x] HTTPS certificate (https://letsencrypt.org)
- [x] Hookup with the `sanomalearning.design` domain name (IT ops)
- [x] Add a "Coming soon" plain text message

**Comment by jpzwarte** [comment]
It can take up to 24 hours for the DNS changes to propagate.

![Image](https://user-images.githubusercontent.com/3968/197809780-3e71cda0-4b8e-4794-bb09-efcc24e245fa.png)
