### ISSUE TITLE
Development of checkbox component

### ISSUE THREAD

**Issue by DanielleRameau** [sanomalearning/design-system#237]
## Description
The Design system needs an checkbox component. Checkboxes allow users to choose one or more options from a limited set of options.

## Requirements
- [x] available in different sizes (md|lg)
- [x] labels
- [x] text and label are clickable
- [x] used with and without text 
- [x] help text

## States
- [x] idle
- [x] checked
- [x] indeterminate
- [x] disabled
- [x] invalid
- [x] focus

## Examples
https://dna.iddinkgroup.com/?path=/story/core_forms-checkbox-documentation--page
https://spectrum.adobe.com/page/checkbox/
https://www.magentaa11y.com/checklist-web/radio/

```[tasklist]
### Tasks
- [ ] Discuss during refinement
```

**Comment by Diaan** [comment]
There's an issue with Voice Over on mac that I have been able to reproduce in all design systems I've tried and also in a codepen I made with just native components: https://codepen.io/dianabroeders/pen/OJoRVJO?editors=1100
Directing the voiceover to the last, disabled, option leaves the focus on the last option before the disabled one, as seen in the image:
![Image](https://user-images.githubusercontent.com/1351956/221213604-f0435f1c-b681-4499-b539-e48c4d565c6c.png)
This causes the user to assume the focus is on option that is currently being read out, but a press of the spacebar or enter key selects the previously focused (read) option.
When you check the "previous" option the feedback from the voice over makes it clear which option you selected, so it shouldn't be too error prone, but still it works a bit weird.
